site_name: asltk
repo_url: https://github.com/LOAMRI/asltk
repo_name: LOAMRI/asltk
edit_uri: tree/main/docs

theme:
  name: material
  language: en
  logo: assets/asltk-favicon.png
  favicon: assets/asltk-favicon.png
  palette:
    scheme: default
    primary: custom
    accent: cyan
  font:
    text: Arial
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.footnote.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes

extra_css:
  - stylesheets/extra.css

nav:
  - 'index.md'
  - 'installation_guide.md'
  - 'getting_started.md'
  - 'faq.md'
  - 'api/asldata.md'
  - 'api/reconstruction.md'
  - 'api/utils.md'
  - 'contribute.md'

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [asltk]