name: CI_develop
on: 
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repo
        uses: actions/checkout@v4.2.0


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  

      - name: Install Poetry
        run: pip install poetry

      - name: Install asltk project dependecies
        run: poetry install

      - name: Run project tests
        run: poetry run task test --cov-report=xml --ignore-glob='./asltk/scripts/*.py'

      - name: Show-up test coverage (codecov)
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  windows:
    runs-on: windows-latest
    
    steps:
      - name: Clone repo
        uses: actions/checkout@v4.2.0


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  

      - name: Install Poetry
        run: pip install poetry

      - name: Install asltk project dependecies
        run: poetry install

      - name: Run project tests
        run: poetry run task test --cov-report=xml --ignore-glob='./asltk/scripts/*.py'

      - name: Show-up test coverage (codecov)
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  mac:
    runs-on: macos-latest
    
    steps:
      - name: Clone repo
        uses: actions/checkout@v4.2.0


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  

      - name: Install Poetry
        run: pip install poetry

      - name: Install asltk project dependecies
        run: poetry install

      - name: Run project tests
        run: poetry run task test --cov-report=xml --ignore-glob='./asltk/scripts/*.py'

      - name: Show-up test coverage (codecov)
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
