name: Deploy
on: [push, pull_request]

job:
  test:
    name: Test project - Linux
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
      uses: actions/checkout@v4.2.0 git clone git@github.com:LOAMRI/asltk.git


      - name: Setup Python
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.10'  

      - name: Install Poetry
        run: pip install poetry

      - name: Install asltk project dependecies
        run: poetry install

      - name: Run project tests
        run: poetry run task test --cov-report=xml

      - name: Show-up test coverage (codecov)
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

